### PR TITLE
Updated art asset leak download link to a different one that isn't down

### PR DESCRIPTION
**Pull request by RockstarAdvancedGameEngine**

### CODE REVIEW

**Comment by AnomaliesGentoolman** [comment]
Hmm, already the link isn't down i tested it. not needed to make this change.
If my link got down, i will merge this pull request.

**Comment by RockstarAdvancedGameEngine** [comment]
Hmm that's weird, for me I get a connection reset error.

**Comment by AnomaliesGentoolman** [comment]
> Hmm that's weird, for me I get a connection reset error.

So weird, I can actually download the whole file without any problems.

**Comment by RockstarAdvancedGameEngine** [comment]
lol maybe my ISP blocked it or something cus when I use a VPN its fine, guess it was nothing

**Comment by AnomaliesGentoolman** [comment]
yeah maybe.

**Pull request closed without merging**
